### ISSUE TITLE
Pls do this

### ISSUE THREAD

**Issue by RaunterTheSlime** [richie0866/MidiPlayer#14] opened 2022-04-15 14:22 UTC
Make a slider that changes the speed that the midi is played so when a stranger says "play it slow so we kbow your not cheating" you could actually play it slow and maybe add the option to play it fast

**Comment by ZStrikeGit** [comment] 2022-04-15 23:00
the developer said that he is no longer maintaining the script, but you can always try adding this yourself!

**Comment by richie0866** [comment] 2022-04-20 00:35
Duplicate of #3

**Closed as completed by richie0866** 2022-04-20 00:35 UTC
