### ISSUE TITLE
the gui doesnt show up when you execute with krnl

### ISSUE THREAD

**Issue by forsenforsen** [richie0866/MidiPlayer#6] opened 2022-01-21 15:35 UTC
![Screenshot 2022-01-21 233427](https://user-images.githubusercontent.com/91766243/150554850-8562901b-4792-4e9f-a172-aeaa00417ab0.png)

**Comment by richie0866** [comment] 2022-01-25 22:14
Duplicate of #4

**Closed by richie0866** 2022-01-25 22:14 UTC
